name: Build and publish docker image

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Build, tag, and push
        run: |
          # TAG=$(git describe --tags --always)
          TAG=latest
          docker build -t ghcr.io/artyom/mdlinks:$TAG .
          docker push ghcr.io/artyom/mdlinks:$TAG
